deducible:
  handler: src/Deducible/app.handler
  name: ${self:custom.regions.abrev.${opt:stage}}COM${opt:stage}DEDUCIBLEV1
  description: FUNCION PARA PROCESAR DATOS DEDUCIBLES DE TEXTO PLANO
  package:
    exclude:
      - node_modules/**
